<b>NumPy</b> library is the core library for scientific computing in Python. It provides a high-performance multidimensional array objects, and tools for working wiht arrays.
<br>
It is imported by using the following library

In [1]:
import numpy as np

<b>Creating Arrays</b>

In [10]:
a= np.array([1,2,3])
b= np.array([(1,2,3),(4,5,6)],dtype=int)
c= np.array([[(1.5,2,3),(4,5,6)],[(3,4,5),(4,5,6)]],dtype=float)

In [11]:
#1D ARRAY
a

array([1, 2, 3])

In [12]:
#2D ARRAY
b

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#3D array
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 4. , 5. ],
        [4. , 5. , 6. ]]])

Creating an array of zeroes

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creating an array of ones

In [16]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

Creating an array of evenly spaced values(step value)

In [20]:
# np.arange(start_val,end_val,step_val)
d = np.arange(10,25,5)
d

array([10, 15, 20])

Creating an array of evenly spaced values(number of samples)

In [21]:
# np.arange(start_val,end_val,step_val)
np.linspace(0,9,6)


array([0. , 1.8, 3.6, 5.4, 7.2, 9. ])

Creating a constant array

In [23]:
e= np.full((2,3),7)
e

array([[7, 7, 7],
       [7, 7, 7]])

Creating a 3x3 identity matrix

In [25]:
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creating an array with random values

In [27]:
np.random.random((2,2))

array([[0.10628543, 0.78191644],
       [0.99951405, 0.91762847]])

Creating an empty array (It is filled with garbage values)

In [29]:
np.empty((3,2))

array([[0. , 1.8],
       [3.6, 5.4],
       [7.2, 9. ]])

<b>Data Types</b>

In [33]:
#(np.int64)
type(54)

int

In [34]:
#(np.float32)
type(2.0)

float

In [35]:
#(np.complex)
type(-3 + 2j)

complex

In [36]:
#(np.bool)
type(True)

bool

In [38]:
#(np.string_)
type('obj')

str

In [39]:
np.string_

numpy.bytes_

In [40]:
np.unicode_

numpy.str_

In [41]:
np.object

object

<b>Inspecting the Array </b>

In [49]:
a.shape #array dimensions

(3,)

In [50]:
b.shape #array dimensions

(2, 3)

In [51]:
c.shape #array dimensions

(2, 2, 3)

In [52]:
#length of array 
print(len(a))
print(len(b))
print(len(c))

3
2
2


In [53]:
b.ndim #number of array dimensions

2

In [54]:
c.ndim #number of array dimensions

3

In [55]:
e.size #number of array elements

6

In [57]:
b.dtype #Data Type of array elements

dtype('int32')

In [58]:
c.dtype #Data Type of array elements

dtype('float64')

In [59]:
b.dtype.name #Name of data type

'int32'

In [60]:
#Converting the array into a different datatype
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

ASKING FOR HELP

In [65]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


### <b>Array Mathematics</b>

<b>Arithmetic Operations</b>

In [67]:
g=a-b
g

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [68]:
np.subtract(a,b)

array([[ 0,  0,  0],
       [-3, -3, -3]])

In [69]:
b+a

array([[2, 4, 6],
       [5, 7, 9]])

In [70]:
np.add(b,a)

array([[2, 4, 6],
       [5, 7, 9]])

In [71]:
a/b

array([[1.  , 1.  , 1.  ],
       [0.25, 0.4 , 0.5 ]])

In [72]:
np.divide(b,a)

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [73]:
a*b

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [74]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [75]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [76]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [77]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [78]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [79]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [80]:
e.dot(f)

array([[7., 7., 7.],
       [7., 7., 7.]])

<b>Comparison</b>

In [81]:
a==b

array([[ True,  True,  True],
       [False, False, False]])

In [82]:
a<2

array([ True, False, False])

In [83]:
np.array_equal(a,b)

False

<b>Aggregate Functions</b>

In [84]:
a.sum()

6

In [86]:
a.min()

1

In [87]:
b.max(axis=0)

array([4, 5, 6])

In [88]:
b.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [89]:
a.mean()

2.0

In [95]:
np.std(b) #Standard deviation

1.707825127659933

In [96]:
np.median(b) #median

3.5

In [97]:
np.corrcoef(a) #Correlation coefficient

1.0

<b>Copying Arrays</b>

In [99]:
h = a.view()
h

array([1, 2, 3])

In [100]:
np.copy(a)

array([1, 2, 3])

In [102]:
h=a.copy()
h

array([1, 2, 3])

<b>Sorting Arrays</b>

In [104]:
a.sort()
a

array([1, 2, 3])

In [105]:
b.sort()
b

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
c.sort(axis=0)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 4. , 5. ],
        [4. , 5. , 6. ]]])

### Subsetting, Slicing, indexing

Subsetting

In [108]:
a[2]

3

In [109]:
b[1,2]

6

Slicing

In [110]:
a[0:2]

array([1, 2])

In [112]:
b[0:2,1]

array([2, 5])

In [113]:
b[:1]

array([[1, 2, 3]])

In [114]:
c[1,]

array([[3., 4., 5.],
       [4., 5., 6.]])

In [115]:
a[::-1]

array([3, 2, 1])

Boolean Indexing

In [117]:
a[a<3]

array([1, 2])

Fancy Indexing

In [119]:
b[[1,0,1,0],[0,1,2,0]] #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4, 2, 6, 1])

In [122]:
b[[1,0,1,0]][:,[0,1,2,0]]
  #Select a subset of the matrix’s rows and columns

array([[4, 5, 6, 4],
       [1, 2, 3, 1],
       [4, 5, 6, 4],
       [1, 2, 3, 1]])

<b>Array Manipulation</b>

In [123]:
#Transposing array
i = np.transpose(b)

In [124]:
i.T

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
#Changing array shape

#Flatten the array
b.ravel()

array([1, 2, 3, 4, 5, 6])

In [126]:
#Reshaping without changing the data
g.reshape(3,-2)

array([[ 0,  0],
       [ 0, -3],
       [-3, -3]])

In [129]:
#Adding/Removing Elements

c.resize((2,6))
c

array([[1.5, 2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 4. , 5. , 6. ]])

In [130]:
np.append(h,g)

array([ 1,  2,  3,  0,  0,  0, -3, -3, -3])

In [131]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [132]:
np.delete(a,[1])

array([1, 3])

In [133]:
#Combining Arrays

np.concatenate((a,d),axis=0) #concatenate arrays

array([ 1,  2,  3, 10, 15, 20])

In [134]:
np.vstack((a,b)) #Stack arrays vertically (row-wise)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
np.r_[e,f] #Stack arrays vertically (row-wise)

array([[7., 7., 7.],
       [7., 7., 7.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [138]:
np.column_stack((a,d)) #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [139]:
np.c_[a,d] #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [140]:
#SPLITTING ARRAYS
np.hsplit(a,3) #Split the array horizontally at the 3rd index


[array([1]), array([2]), array([3])]

In [141]:
np.vsplit(c,2) #Split the array vertically at the 2nd index

[array([[1.5, 2. , 3. , 4. , 5. , 6. ]]), array([[3., 4., 5., 4., 5., 6.]])]