## Starting with Python for Data Science

This notebook holds the basics of python needed for Data Science. It is a starting guide for beginners in python and programming. 

#### 1. Data Types and Variables

In [7]:
x=5
y=5.0
z="string"
l=[1,2,3]
t=(1,2,3)
d={'one':1, 'two':2, 'three':3}

In [8]:
print(type(x))
print(type(y))
print(type(z))
print(type(l))
print(type(t))
print(type(d))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


The various data types are int, float, str, list, tuple, dict for integer, floatint point, string, list, tuple, dictionary respectively.

In [9]:
#Sum of two variables
x+2

7

In [10]:
#Subtraction of two variables
x-2

3

In [11]:
#Multiplication of two variables
x*2

10

In [14]:
#Remainder of a variable
x%2

1

In [15]:
#Exponent of a variable
x**2

25

In [16]:
#Division of a variable
x/float(2)

2.5

The above command is also an example of type conversion. As the result of x/2 is a value rounded to give an integer, the exact answer(in decimal) is reported by using type conversion to convert the int to float.
##### Other examples of Type Conversion

In [18]:
str(5)

'5'

Returns a string of character '5' when input is integer 5.

In [19]:
float(5)

5.0

In [20]:
print(bool(1))
print(bool(0))

True
False


1 represents True and 0 represents False.

#### 2. Strings and String Operations

In [21]:
my_string='ThisIsAString'
my_string

'ThisIsAString'

In [22]:
my_string*2

'ThisIsAStringThisIsAString'

In [23]:
my_string + '-First'

'ThisIsAString-First'

In [24]:
't' in my_string
#returns a bool value as it checks for the character 't' in the string.

True

In [26]:
print(my_string[4])
print(my_string[4:10])

I
IsAStr


In [27]:
my_string.upper()
#string to uppercase

'THISISASTRING'

In [28]:
my_string.lower()
#string to lowercase

'thisisastring'

In [30]:
my_string.count('s')
#count string elements

2

In [31]:
my_string.replace('A','a')
#replacing string elements

'ThisIsaString'

#### 3. Asking for help

In [35]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

#### 4. Lists, List Operations and List Methods

In [36]:
a='is'
b='great'
my_list=['my', 'list', a, b]
int_list=[[1,2,3,4],[4,5,6,7]]

In [37]:
print(my_list)
print(int_list)

['my', 'list', 'is', 'great']
[[1, 2, 3, 4], [4, 5, 6, 7]]


In [38]:
#selecting item at index 1
my_list[1]

'list'

This shows that list indexing begins from 0 (similar to as in arrays)

In [39]:
#Selecting the second last item from the list
my_list[-2]

'is'

In [40]:
#Selecting items at index from 0 to 2
my_list[0:2]

['my', 'list']

The upper limit is not included in index.

In [41]:
#selecting items before index 3
print(my_list[:3])

#selecting items after index 1
print(my_list[1:])

['my', 'list', 'is']
['list', 'is', 'great']


In [42]:
#copying the list/printing the whole list
my_list[:]

['my', 'list', 'is', 'great']

In [43]:
#SUBSET LISTS OF LISTS
int_list[1][3]

7

In [44]:
int_list[0][:]

[1, 2, 3, 4]

In [47]:
my_list+['and', 'simple']

['my', 'list', 'is', 'great', 'and', 'simple']

In [48]:
my_list *2

['my', 'list', 'is', 'great', 'my', 'list', 'is', 'great']

In [54]:
#LIST METHODS

my_list.index(a)

2

In [55]:
my_list.index(b)

3

In [56]:
#Count an item 
my_list.count(a)

1

In [61]:
#append at the end
my_list.append('!')
my_list

['my', 'list', 'is', 'great', '!']

In [62]:
#remove an item
my_list.remove('!')
my_list

['my', 'list', 'is', 'great']

In [63]:
#remove an item 
del(my_list[0:1])
my_list

['list', 'is', 'great']

In [67]:
#Reverse the list
my_list.reverse()
my_list

['great', 'is', 'list']

In [68]:
#Append an item
my_list.extend('!')
my_list

['great', 'is', 'list', '!']

In [69]:
#remove an item
my_list.pop(-1)
my_list

['great', 'is', 'list']

In [70]:
#Insert an item
my_list.insert(0,'!')
my_list

['!', 'great', 'is', 'list']

In [71]:
#Sorting the list
my_list.sort()

In [72]:
my_list

['!', 'great', 'is', 'list']

#### 5. Most Frequently used libraries

In [73]:
#import libraries
import matplotlib
import numpy as np

#selective import
from math import pi

<b> Talking about NumPy Arrays

In [74]:
my_list=[1,2,3,4]
my_array=np.array(my_list)
my_array

array([1, 2, 3, 4])

In [75]:
my_array[1]

2

In [76]:
my_array[0:2]

array([1, 2])

In [78]:
# 2D numpy array
my_2darray=np.array([[2,3,4],[4,5,6]])
my_2darray[:,0]

array([2, 4])

In [79]:
my_array > 3

array([False, False, False,  True])

In [80]:
my_array * 2

array([2, 4, 6, 8])

In [81]:
my_array + np.array([5,6,7,8])

array([ 6,  8, 10, 12])

In [82]:
my_array.shape

(4,)

In [83]:
my_2darray.shape

(2, 3)

In [87]:
np.append([5],my_array)

array([5, 1, 2, 3, 4])

In [88]:
np.insert(my_array,1,5)

array([1, 5, 2, 3, 4])

In [89]:
np.delete(my_array,[1])

array([1, 3, 4])

In [90]:
np.mean(my_array)

2.5

In [91]:
np.median(my_array)

2.5

In [92]:
np.std(my_array)

1.118033988749895